# --- 基本設定 (Nix側で設定済みなら不要ですが、残しておいてもOK) ---
set-option -g status-position bottom
set -ag terminal-overrides ",*:RGB"

# --- 操作設定 ---
# ペイン移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# クリップボード連携
set -s set-clipboard on
# bind-key -T copy-mode-vi v send -X begin-selection
# bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel "wl-copy"
# bind-key -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel "wl-copy"
# bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"

# ポップアップ設定
bind -n M-t if-shell -F '#{==:#{session_name},popup}' \
  'detach-client' \
  'display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "tmux new-session -A -s popup"'
