# Terminal and clipboard
set -g status-position bottom
set -ag terminal-overrides ",*:RGB"
set -g update-environment "DISPLAY SSH_ASKPASS SSH_AUTH_SOCK SSH_AGENT_PID SSH_CONNECTION WINDOWID XAUTHORITY LANG LC_ALL LC_CTYPE"
set -s set-clipboard on

# Navigation and selection
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -T copy-mode-vi v send -X begin-selection

# Popups
bind -n M-t if-shell -F '#{==:#{session_name},popup}' \
  'detach-client' \
  'display-popup -d "#{pane_current_path}" -w 90% -h 90% -E "tmux new-session -A -s popup"'
bind b display-popup -d "#{pane_current_path}" -x 0 -y 65% -w 100% -h 35% -E "tmux new-session -A -s bottom"
